version: '3.8'

services:
  db_postgresql:
    image: bitnami/postgresql:16.3.0
    env_file: ./.env
    volumes:
      - postgresql_data:/bitnami/postgresql
  sso_keycloak:
    image: bitnami/keycloak:24.0.5
    # container: keycloak-24.0.5
    ports:
      - "8080:8080"
    expose:
      - "8080"
    env_file: ./.env
    depends_on:
      - db_postgresql
    volumes:
      - ./mynewthem:/opt/bitnami/keycloak/themes/mynewtheme
volumes:
  postgresql_data:
    driver: local
    